### ISSUE TITLE
It's still alive?

### ISSUE THREAD

**Issue by ondonadas** [stevenylai/ralink_sdk#1]
Hi @stevenylai 

Recently I've buy some TOP-AP01-38 modules (http://www.toplink-tech.com/Product/details/16) and I've downloaded (somewhere on baidu) Ralink 3.6.0.0 SDK (kernel 2.6)

I wonder If I can use your SDK (4.0.0) with this modules. Please, are you aware of it?

Thanks for your time
Sergio

**Comment by ondonadas** [comment]
bump

**Comment by stevenylai** [comment]
Sorry for the late reply. I got the SDK from Ralink sales. They still have updates from time to time but it's probably not gonna make any difference as all their SDKs are based on the same old Linux 2.6 kernel and ancient gcc3.3 compiler.

I'm not sure about your board. It looks very much the same as the board I've been using but I can't guarantee anything. You'll probably need a serial port to interact with the firmware/bootloader.

**Comment by ondonadas** [comment]
Thank you


Finally I'm using 3.6 sdk, as 4.0 seems to look the same.
For those modules the sdk is
